# Linear Regression with NumPy Functions Explained

This notebook explains key NumPy functions step by step and shows how they are used in a Linear Regression example.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

## 1. Create Example Data

In [ ]:


np.random.seed(0)
x = np.linspace(0, 10, 100)
y = np.linspace(0, 5, 100)
z = 2*x + 3*y + np.random.randn(100)  # linear relation with some noise

In [11]:
np.array([x, y])


array([[ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
         0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
         1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
         1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
         2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
         2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
         3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
         3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
         4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
         4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
         5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
         5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
         6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
         6.56565657,  6.66666667,  6.76767677,  6.8

## 2. NumPy Functions Explained

### `np.array` and `reshape`

In [5]:
arr = np.array([x, y])
print("Shape before reshape:", arr.shape)
arr_reshaped = arr.reshape(100, 2)
print("Shape after reshape:", arr_reshaped.shape)

Shape before reshape: (2, 100)
Shape after reshape: (100, 2)


### `np.linspace`
Generates evenly spaced values.

In [8]:
lin_example = np.linspace(0, 1, 5)
print("Linspace example:", lin_example)

# np.linspace(start, stop, n) 

# generates evenly spaced numbers.
# Here it creates n equally spaced values between the start and stop

Linspace example: [0.   0.25 0.5  0.75 1.  ]


### `np.meshgrid`
Turns 1D arrays into coordinate matrices.

In [9]:
a = np.array([1,2,3])
b = np.array([4,5])
mg_x, mg_y = np.meshgrid(a, b)
print("Meshgrid X:\n", mg_x)
print("Meshgrid Y:\n", mg_y)

Meshgrid X:
 [[1 2 3]
 [1 2 3]]
Meshgrid Y:
 [[4 4 4]
 [5 5 5]]


### `np.ravel`, `np.vstack`, and transpose

In [ ]:
print("Flattened array:", mg_x.ravel())
stacked = np.vstack((mg_x.ravel(), mg_y.ravel()))
print("Stacked shape:", stacked.shape)
print("Transposed shape:", stacked.T.shape)

## 3. Fit Linear Regression

In [ ]:
lr = LinearRegression()
lr.fit(np.array([x,y]).reshape(100,2), z)

## 4. Create Grid for Prediction

In [ ]:
x_input = np.linspace(x.min(), x.max(), 10)
y_input = np.linspace(y.min(), y.max(), 10)
xGrid, yGrid = np.meshgrid(x_input, y_input)

final = np.vstack((xGrid.ravel().reshape(1,100), yGrid.ravel().reshape(1,100))).T
z_final = lr.predict(final).reshape(10,10)

## 5. Plot Results

In [ ]:
fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(xGrid, yGrid, z_final, cmap='viridis', alpha=0.7)
ax.scatter(x, y, z, color='r')
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
plt.show()