# NumPy

## The Basics of NumPy Arrays
Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array. This section will present several examples of using NumPy array manipulation to access data.

We'll cover a few categories of basic array manipulations here:

## Attributes of arrays:
- Determining the size, shape of an array
- Indexing of arrays: Getting and setting the value of individual array elements
- Slicing of arrays: Getting and setting smaller subarrays within a larger array

In [1]:
import numpy as np

In [2]:
a = np.array([9,10,17,3]) # One-dimensional array

b = np.array([[3, 5, 2, 4], 
              [7, 6, 8, 8],
              [1, 6, 7, 7]])  # Two-dimensional array

c = np.array([[8, 1, 5, 9], 
              [8, 9, 4, 3],
              [0, 3, 5, 0]])  # Two-dimensional array

In [3]:
print("Dimenssion of array a is : ", a.ndim)
print("Shape of array a is :", a.shape)
print("Size of array a is = ", a.size)

Dimenssion of array a is :  1
Shape of array a is : (4,)
Size of array a is =  4


In [7]:
print("Dimenssion of array b is : ", b.ndim)
print("Shape of array b is :", b.shape)
print("Size of array b is 3 * 4 = ", b.size)

Dimenssion of array b is :  2
Shape of array b is : (3, 4)
Size of array b is 3 * 4 =  12


### Operations on Numpy Array

In [4]:
#multiplying a constant with array
scalar =  c*4
print(scalar)

[[32  4 20 36]
 [32 36 16 12]
 [ 0 12 20  0]]


In [9]:
c

array([[8, 1, 5, 9],
       [8, 9, 4, 3],
       [0, 3, 5, 0]])

In [11]:
#adding b and c because they have same dimensions
add = b + c
print(add)

[[11  6  7 13]
 [15 15 12 11]
 [ 1  9 12  7]]


In [7]:
# element wise multipication
multiply = b*c 
print(multiply)

[[24  5 10 36]
 [56 54 32 24]
 [ 0 18 35  0]]


In [5]:
#taking square of every element in c
square = b**2
print(square)

[[ 9 25  4 16]
 [49 36 64 64]
 [ 1 36 49 49]]


In [9]:
#are elements of b > than c
logical= b > c
print(logical)

[[False  True False False]
 [False False  True  True]
 [ True  True  True  True]]


In [14]:
b

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [6]:
np.min(b)           # Minimum of the flattened array

np.int64(1)

In [7]:
np.min(b, axis=0)   # Minima along the first axis which means the minimum in first column,second column and so on.

array([1, 5, 2, 4])

In [ ]:
np.min(b, axis=1) # Minima along the second axis which means the minimum of first row,second row and so on.

array([2, 6, 1])

In [13]:
np.max(b)         # Maximum of the flattened array

8

### Array Indexing: Accessing Single Elements 

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [19]:
a

array([ 9, 10, 17,  3])

In [8]:
a[0]

np.int64(9)

In [9]:
a[0:3]

array([ 9, 10, 17])

In [10]:
a[-1]

np.int64(3)

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices

In [11]:
b

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
b[0, 0]

np.int64(3)

In [13]:
b[2, -1]

np.int64(7)

In [14]:
b[-1,-2]

7

In [26]:
b[0, 0] = 12
b

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Pandas

Pandas will be a major tool of interest throughout the course. It
contains data structures and data manipulation tools designed to make data cleaning
and analysis fast and easy in Python. Pandas is often used in tandem with numerical
computing tools like NumPy and SciPy, analytical libraries like statsmodels and
scikit-learn, and data visualization libraries like matplotlib.Throughout the rest of the notebook, I use the following import convention for pandas:
- *import pandas as pd* .
Thus, whenever you see pd. in code, it’s referring to pandas

In [18]:
import pandas as pd  #for data analysis and manipulation

### Importing data using Pandas Data Frame

A DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type (numeric, string,boolean, etc.). The DataFrame has both a row and column index.

In [17]:
data = pd.read_csv('car_data.csv')

In [29]:
data

Car_Name  Year  Selling_Price  Kms_Driven Fuel_Type Seller_Type  \
0       ritz  2014           3.35       27000    Petrol      Dealer   
1        sx4  2013           4.75       43000    Diesel      Dealer   
2       ciaz  2017           7.25        6900    Petrol      Dealer   
3    wagon r  2011           2.85        5200    Petrol      Dealer   
4      swift  2014           4.60       42450    Diesel      Dealer   
..       ...   ...            ...         ...       ...         ...   
296     city  2016           9.50       33988    Diesel      Dealer   
297     brio  2015           4.00       60000    Petrol      Dealer   
298     city  2009           3.35       87934    Petrol      Dealer   
299     city  2017          11.50        9000    Diesel      Dealer   
300     brio  2016           5.30        5464    Petrol      Dealer   

    Transmission  Owner  
0         Manual      0  
1         Manual      0  
2         Manual      0  
3         Manual      0  
4         Manual      0  
..           ...    ...  
296       Manual      0  
297       Manual      0  
298       Manual      0  
299       Manual      0  
300       Manual      0  

[301 rows x 8 columns]

### Some important methods to manipulate and analyze data

In [30]:
data.head() #the head method selects only the first five rows

Car_Name  Year  Selling_Price  Kms_Driven Fuel_Type Seller_Type  \
0     ritz  2014           3.35       27000    Petrol      Dealer   
1      sx4  2013           4.75       43000    Diesel      Dealer   
2     ciaz  2017           7.25        6900    Petrol      Dealer   
3  wagon r  2011           2.85        5200    Petrol      Dealer   
4    swift  2014           4.60       42450    Diesel      Dealer   

  Transmission  Owner  
0       Manual      0  
1       Manual      0  
2       Manual      0  
3       Manual      0  
4       Manual      0

We see that our data is mix of both Numeric and Categorical attributes. The attributes Selling_Price is in ($ 100,000). Let us see the summary of the data

In [31]:
data.describe() #describe method gives 8 point summary of our numeric data

Year  Selling_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296   36947.205980    0.043189
std       2.891554       5.082812   38886.883882    0.247915
min    2003.000000       0.100000     500.000000    0.000000
25%    2012.000000       0.900000   15000.000000    0.000000
50%    2014.000000       3.600000   32000.000000    0.000000
75%    2016.000000       6.000000   48767.000000    0.000000
max    2018.000000      35.000000  500000.000000    3.000000

In [31]:
print("The shape of data is : ",data.shape) #to see number of rows and columns in data

The shape of data is :  (5060, 11)


In [34]:
print(data.columns) #to display all the columns in our data

Index(['Car_Name', 'Year', 'Selling_Price', 'Kms_Driven', 'Fuel_Type',
       'Seller_Type', 'Transmission', 'Owner'],
      dtype='object')


In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Kms_Driven     301 non-null    int64  
 4   Fuel_Type      301 non-null    object 
 5   Seller_Type    301 non-null    object 
 6   Transmission   301 non-null    object 
 7   Owner          301 non-null    int64  
dtypes: float64(1), int64(3), object(4)
memory usage: 18.9+ KB


In [36]:
data.isnull().sum() #isnull methods returns Boolean value whether data is missing and sum will return its count

Car_Name         0
Year             0
Selling_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [37]:
data["Kms_Driven"] #to select an attribute from data frame

0      27000
1      43000
2       6900
3       5200
4      42450
       ...  
296    33988
297    60000
298    87934
299     9000
300     5464
Name: Kms_Driven, Length: 301, dtype: int64

In [39]:
#The following example passes a function and checks the value of each element in series and returns low, normal or High accordingly.
def price_range(num): 
  
    if num < 5: 
        return "Low"
  
    elif num >= 5 and num < 10: 
        return "Normal"
  
    else: 
        return "High"

In [40]:
#take an attribute 
Selling_price = data["Selling_Price"]

In [41]:
Selling_price

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...  
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [42]:
# passing function to apply and storing returned series in new 
new = Selling_price.apply(price_range)

In [43]:
data['Price Category'] = new #create new column in the dataset

In [44]:
data

Car_Name  Year  Selling_Price  Kms_Driven Fuel_Type Seller_Type  \
0       ritz  2014           3.35       27000    Petrol      Dealer   
1        sx4  2013           4.75       43000    Diesel      Dealer   
2       ciaz  2017           7.25        6900    Petrol      Dealer   
3    wagon r  2011           2.85        5200    Petrol      Dealer   
4      swift  2014           4.60       42450    Diesel      Dealer   
..       ...   ...            ...         ...       ...         ...   
296     city  2016           9.50       33988    Diesel      Dealer   
297     brio  2015           4.00       60000    Petrol      Dealer   
298     city  2009           3.35       87934    Petrol      Dealer   
299     city  2017          11.50        9000    Diesel      Dealer   
300     brio  2016           5.30        5464    Petrol      Dealer   

    Transmission  Owner Price Category  
0         Manual      0            Low  
1         Manual      0            Low  
2         Manual      0         Normal  
3         Manual      0            Low  
4         Manual      0            Low  
..           ...    ...            ...  
296       Manual      0         Normal  
297       Manual      0            Low  
298       Manual      0            Low  
299       Manual      0           High  
300       Manual      0         Normal  

[301 rows x 9 columns]

In [45]:
# Check distribution of categorical column
data['Price Category'].value_counts()

Low       193
Normal     80
High       28
Name: Price Category, dtype: int64

In [19]:
data =pd.read_excel("PUCIT General Merit List 2020.xlsx")

In [20]:
data

Sr No.          Candidate Name            Father Name      Form_ID  \
0          1  munazza shahzad mughal       muhammad shahzad   BF52032021   
1          2  munazza shahzad mughal       muhammad shahzad  BF52031234z   
2          3             laiba zahid          zahid hussain   BF62033328   
3          4         hanaan ali shah         wajid ali shah   BF52032668   
4          5             ayesha ayub      ayub sabir mughal   BF62035772   
...      ...                     ...                    ...          ...   
5055    5056                  abeeha             rehmat ali   BF52034050   
5056    5057          fariha khurram        khurram rafique   BF62034810   
5057    5058    muhammad akif rashid  muhammad rashid iqbal  BF52031310z   
5058    5059           rashid minhas         muhammad sabir   BF62034643   
5059    5060            nisha yousaf        muhammad yousaf   BF52031550   

      Matric Obtain  Matric Max  Inter Obtain  Inter Max  Inter Year  \
0              1073        1100          1060       1100        2020   
1              1073        1100          1060       1100        2020   
2              1053        1100          1061       1100        2020   
3              1066        1100          1054       1100        2020   
4               864         900          1056       1100        2020   
...             ...         ...           ...        ...         ...   
5055            549        1100           479       1100        2020   
5056            517        1100           484       1100        2020   
5057            526        1100           205        510        2020   
5058            529        1100           452       1100        2020   
5059            818        1100           301       1100        2019   

      Hafiz Quran  Aggregate  
0               0  96.600000  
1               0  96.600000  
2               0  96.309091  
3               0  96.036364  
4               0  96.000000  
...           ...        ...  
5055            0  44.818182  
5056            0  44.600000  
5057            0  42.866242  
5058            0  42.490909  
5059            0  36.763636  

[5060 rows x 11 columns]

In [21]:
data.head()

Sr No.          Candidate Name        Father Name      Form_ID  \
0       1  munazza shahzad mughal   muhammad shahzad   BF52032021   
1       2  munazza shahzad mughal   muhammad shahzad  BF52031234z   
2       3             laiba zahid      zahid hussain   BF62033328   
3       4         hanaan ali shah     wajid ali shah   BF52032668   
4       5             ayesha ayub  ayub sabir mughal   BF62035772   

   Matric Obtain  Matric Max  Inter Obtain  Inter Max  Inter Year  \
0           1073        1100          1060       1100        2020   
1           1073        1100          1060       1100        2020   
2           1053        1100          1061       1100        2020   
3           1066        1100          1054       1100        2020   
4            864         900          1056       1100        2020   

   Hafiz Quran  Aggregate  
0            0  96.600000  
1            0  96.600000  
2            0  96.309091  
3            0  96.036364  
4            0  96.000000

In [22]:
data.describ()

AttributeError: 'DataFrame' object has no attribute 'describ'

In [23]:
data.describe()

Sr No.  Matric Obtain   Matric Max  Inter Obtain    Inter Max  \
count  5060.000000    5060.000000  5060.000000   5060.000000  5060.000000   
mean   2530.500000     926.245850  1095.703162    847.041502  1103.399209   
std    1460.840511     108.119547    30.233663    220.860956   254.500578   
min       1.000000     337.000000   520.000000    174.000000   200.000000   
25%    1265.750000     873.000000  1100.000000    767.000000  1100.000000   
50%    2530.500000     954.500000  1100.000000    864.000000  1100.000000   
75%    3795.250000    1007.000000  1100.000000    929.000000  1100.000000   
max    5060.000000    1197.000000  1350.000000   3050.000000  3550.000000   

        Inter Year  Hafiz Quran    Aggregate  
count  5060.000000  5060.000000  5060.000000  
mean   2019.837154     1.256917    78.429528  
std       0.452490     4.854190     9.356726  
min    2012.000000     0.000000    36.763636  
25%    2020.000000     0.000000    72.990909  
50%    2020.000000     0.000000    80.146122  
75%    2020.000000     0.000000    85.443825  
max    2020.000000    20.000000    96.600000

In [37]:
print(data.shape)

(5060, 11)


In [41]:
data.isnull()

Sr No.  Candidate Name  Father Name  Form_ID  Matric Obtain  Matric Max  \
0      False           False        False    False          False       False   
1      False           False        False    False          False       False   
2      False           False        False    False          False       False   
3      False           False        False    False          False       False   
4      False           False        False    False          False       False   
...      ...             ...          ...      ...            ...         ...   
5055   False           False        False    False          False       False   
5056   False           False        False    False          False       False   
5057   False           False        False    False          False       False   
5058   False           False        False    False          False       False   
5059   False           False        False    False          False       False   

      Inter Obtain  Inter Max  Inter Year  Hafiz Quran  Aggregate  
0            False      False       False        False      False  
1            False      False       False        False      False  
2            False      False       False        False      False  
3            False      False       False        False      False  
4            False      False       False        False      False  
...            ...        ...         ...          ...        ...  
5055         False      False       False        False      False  
5056         False      False       False        False      False  
5057         False      False       False        False      False  
5058         False      False       False        False      False  
5059         False      False       False        False      False  

[5060 rows x 11 columns]

In [42]:
data.isnull().sum()

Sr No.            0
Candidate Name    0
Father Name       0
Form_ID           0
Matric Obtain     0
Matric Max        0
Inter Obtain      0
Inter Max         0
Inter Year        0
Hafiz Quran       0
Aggregate         0
dtype: int64

In [43]:
data["Candidate Name"]

0       munazza shahzad mughal
1       munazza shahzad mughal
2                  laiba zahid
3              hanaan ali shah
4                  ayesha ayub
                 ...          
5055                    abeeha
5056            fariha khurram
5057      muhammad akif rashid
5058             rashid minhas
5059              nisha yousaf
Name: Candidate Name, Length: 5060, dtype: object

In [45]:
data["Candidate Name"][4]

'ayesha ayub'